### ISSUE TITLE
Add brief Style Selection FG page to https://fieldguide.automattic.com/ftm-onboarding-flows/

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/ganon-issues#129]
# Description
When this feature is ready to ship, add a FG page to PCYsg-D3w-p2

# Tasks
- [ ] brief intro to idea
- [ ] links to core PRs/info
- [ ] any tech documentation that might be helpful for next dev
