### ISSUE TITLE
Add Pattern Assember FG page to https://fieldguide.automattic.com/ftm-onboarding-flows/

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/ganon-issues#130]
# Description
When the Pattern Assembler feature is ready to ship, add a FG page to PCYsg-D3w-p2

# Tasks
- [ ] brief intro to feature
 - [ ] links to core PRs/info
 - [ ] any tech documentation that might be helpful for next dev
 - [ ] bullet points of next work

**Comment by miksansegundo** [comment]
Last week I created the page [Blank Canvas Pattern Assembler ](https://fieldguide.automattic.com/ftm-onboarding-flows/blank-canvas-pattern-assembler/)
